# Generated by Django 2.2.4 on 2019-08-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emailheader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
                ('address', models.TextField()),
            ],
        ),
    ]
