# Generated by Django 2.2.4 on 2019-08-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailfooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('website_url', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField()),
            ],
        ),
    ]
